spring.application.name=Event-booking
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/event_management_system
spring.datasource.username=postgres
spring.datasource.password=noah@123

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=your-256-bit-secret-key-which-is-long-enough
jwt.expiration=3600000
jwt.refresh-expiration=604800000

spring.redis.host=localhost
spring.redis.port=6379